"use client";
import { useMonthlyRevenueQuery } from "@/redux/features/order/orderApi";
import { ResponsiveLine } from "@nivo/line";


const AdminRevenueLineChart = () => {
      const { data:chartData, isLoading, error } = useMonthlyRevenueQuery();

  if (isLoading) return <p>Loading...</p>;
  if (error) return <p>Error fetching revenue data</p>;
  return (
    <div className="h-[450px] w-full rounded-xl shadow-md p-6">
      <h2 className="text-xl font-semibold text-center mb-4 text-primary">
        Monthly Revenue (Line Chart)
      </h2>
      <ResponsiveLine
        data={
          chartData
            ? [
                {
                  id: "Revenue",
                  color: "#0F766E",
                  data: chartData.map((item) => ({
                    x: item.month,
                    y: item.revenue,
                  })),
                },
              ]
            : []
        }
        margin={{ top: 50, right: 80, bottom: 50, left: 60 }}
        xScale={{ type: "point" }}
        yScale={{
          type: "linear",
          min: "auto",
          max: "auto",
          stacked: false,
          reverse: false,
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Month",
          legendOffset: 36,
          legendPosition: "middle",
        }}
        axisLeft={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Revenue ($)",
          legendOffset: -50,
          legendPosition: "middle",
        }}
        pointSize={10}
        pointColor={{ theme: "background" }}
        pointBorderWidth={2}
        pointBorderColor={{ from: "serieColor" }}
        pointLabelYOffset={-12}
        useMesh={true}
        enableSlices="x"
        tooltip={({ point }) => (
          <div className="bg-black text-#0F766E px-2 py-1 rounded">
            <strong>{point.data.xFormatted}</strong>: ${point.data.yFormatted}
          </div>
        )}
      />
      <p className="text-sm text-gray-600 text-center mt-6">
        This chart displays the monthly revenue generated by the platform from order bookings.
      </p>
    </div>
  );
};

export default AdminRevenueLineChart;
